### ISSUE TITLE
Error: [ng:areq] Argument 'module' is not a function, got Object

### ISSUE THREAD

**Issue by kevincaradant** [mattslocum/ng-webworker#30]
Hi 
I  get an error about the module or import. I don't understand why.

I import my file like this:
`import ngWebworker from 'ng-webworker/src/ng-webworker';`

I load the module like this:

```
export const demoModule = angular.module('demo', [
    ngWebworker
]);
```

And at the end, I get this error:

```
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module demo due to:
Error: [$injector:modulerr] Failed to instantiate module {"_invokeQueue":[["$provide","provider",{"0":"Webworker"}]],"_configBlocks":[],"_runBlocks":[],"requires":[],"name":"ngWebworker"} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.8/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at http://localhost:3001/bundle.js:33780:13
    at assertArg (http://localhost:3001/bundle.js:35604:12)
    at assertArgFn (http://localhost:3001/bundle.js:35614:4)
    at http://localhost:3001/bundle.js:38338:12
    at forEach (http://localhost:3001/bundle.js:34033:21)
    at loadModules (http://localhost:3001/bundle.js:38313:6)
    at http://localhost:3001/bundle.js:38330:41
    at forEach (http://localhost:3001/bundle.js:34033:21)
    at loadModules (http://localhost:3001/bundle.js:38313:6)
    at createInjector (http://localhost:3001/bundle.js:38235:20)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=%7B%22_invokeQueue%…20createInjector%20(http%3A%2F%2Flocalhost%3A3001%2Fbundle.js%3A38235%3A20)
    at http://localhost:3001/bundle.js:33780:13
    at http://localhost:3001/bundle.js:38352:16
    at forEach (http://localhost:3001/bundle.js:34033:21)
    at loadModules (http://localhost:3001/bundle.js:38313:6)
    at http://localhost:3001/bundle.js:38330:41
    at forEach (http://localhost:3001/bundle.js:34033:21)
    at loadModules (http://localhost:3001/bundle.js:38313:6)
    at createInjector (http://localhost:3001/bundle.js:38235:20)
    at doBootstrap (http://localhost:3001/bundle.js:35470:21)
    at bootstrap (http://localhost:3001/bundle.js:35491:13)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=demo&p1=Error%3A%20…20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A3001%2Fbundle.js%3A35491%3A13)
```

**Comment by kevincaradant** [comment]
Ok my bad,

the correct syntax is : 

```
export const demoModule = angular.module('demo', [
    'ngWebworker'
]);
```

**Comment by mariotacke** [comment]
Just ran into the same thing. Thanks for posting your solution. It worked for me as well. Would love for the library to export its own name as 'ngWebworker' to reduce confusion.
